[package]
name = "my-mail-client"
version = "0.1.0"
edition = "2018"

[dependencies]
serde = {version = "1", features = ["derive"]}
tokio = {version = "1", features = ["full"]}
sqlx = {version = "0.8", features = ["runtime-tokio", "macros", "sqlite"]}
anyhow = "1"